### ISSUE TITLE
Upload a set of testing Image

### ISSUE THREAD

**Issue by valkjsaaa** [devilhtc/EE367-livephoto#2]

**Comment by devilhtc** [comment]
Yeah we should. I remember you told me we can extract the photo and video from google photos? I'm not using it. Can you upload some test images/footages?

**Comment by valkjsaaa** [comment]
I can directly export image video pair from Photos.app.

**Comment by devilhtc** [comment]
ok let me try it

**Comment by devilhtc** [comment]
yeah it works
file->export->export unmodified ...

**Comment by valkjsaaa** [comment]
Wait a sec. I created a repo dedicated for testing image. We can upload all of them there.

**Comment by valkjsaaa** [comment]
https://github.com/valkjsaaa/EE367-livephoto-resources.git

**Comment by devilhtc** [comment]
can you put them in subdirectory in this main repo?

**Comment by valkjsaaa** [comment]
Yes. I'm working on that. Please commit and push your photo to that repo.

I will use git submodule for this resources folder.
