### ISSUE TITLE
Calculate optical flow

### ISSUE THREAD

**Issue by valkjsaaa** [devilhtc/EE367-livephoto#4]
There are several state-of-the-art methods such as epicflow or deepflow. Deepflow should has api in opencv 3 but epicflow only has source code in C++.

**Comment by valkjsaaa** [comment]
@devilhtc Can you try this first. I'm not so familiar of optical flow.

Also I think we should give a quick try of that implementation in OpenCV, just in case it already works well.

**Comment by devilhtc** [comment]
yeah sure. I'm struggling with opencv right now.

**Comment by devilhtc** [comment]
Can you figure out how to save optical flow as video? I tried to but it does not work. (I've already cast things to 8-bit int but cv2 just refuses to cooperate)
