### ISSUE TITLE
Do clustering in some feature space

### ISSUE THREAD

**Issue by valkjsaaa** [devilhtc/EE367-livephoto#6]
containing flow, color, position etc using clustering algorithms such as primitive k-means or mean-shift?

**Comment by valkjsaaa** [comment]
@devilhtc I'm not sure I understand this. Why do we need to do clustering? Is this for object seperation?

**Comment by devilhtc** [comment]
Oh it's just a standard way to do segmentation - clustering pixels based on their color and position

**Comment by devilhtc** [comment]
you can look for other publications on segmentation. I'm by no means an expert on this.
